package gmail

import (
	"encoding/base64"
	"fmt"
	"mail_cli/app"
	"strings"
	"time"

	gmailapi "google.golang.org/api/gmail/v1"
)

// runRESTTests runs self-tests to verify the program can create labels, insert/move messages, and clean up.
func RunRESTTests(config *Config) error {
	srv, err := GetGmailService(config)
	if err != nil {
		return err
	}

	fmt.Printf("%s Starting Gmail API Integration Tests...\n", app.PrefixInfo)

	// 1. Create a recursive label name
	timestamp := time.Now().UnixNano()
	testLabelName := fmt.Sprintf("test/temp/label-%d", timestamp)
	fmt.Printf("%s Step 1: Creating recursive label %q...\n", app.PrefixInfo, testLabelName)

	createdLabel, err := srv.Users.Labels.Create("me", &gmailapi.Label{
		Name:                  testLabelName,
		LabelListVisibility:   "labelShow",
		MessageListVisibility: "show",
	}).Do()
	if err != nil {
		return fmt.Errorf("failed to create label %q: %w", testLabelName, err)
	}
	labelID := createdLabel.Id
	fmt.Printf("%s Created label successfully (ID: %s).\n", app.PrefixSuccess, labelID)

	// Defer cleanup of the label in case we fail later
	var labelCleanupErr error
	defer func() {
		fmt.Printf("%s Step 5: Deleting recursive label %q...\n", app.PrefixInfo, testLabelName)
		labelCleanupErr = srv.Users.Labels.Delete("me", labelID).Do()
		if labelCleanupErr != nil {
			fmt.Printf("%s Failed to delete label %q: %v\n", app.PrefixError, testLabelName, labelCleanupErr)
		} else {
			fmt.Printf("%s Deleted label %q successfully.\n", app.PrefixSuccess, testLabelName)
		}
	}()

	// 2. Create a fake email inside INBOX
	fmt.Printf("%s Step 2: Inserting a fake email into INBOX...\n", app.PrefixInfo)
	rawMessage := []byte("From: test-sender@example.com\r\n" +
		"To: " + config.Username + "\r\n" +
		"Subject: Integration Test Email\r\n" +
		"\r\n" +
		"This is a temporary test message generated by gmail.\r\n")

	msg := &gmailapi.Message{
		Raw:      base64.URLEncoding.EncodeToString(rawMessage),
		LabelIds: []string{"INBOX"},
	}

	createdMsg, err := srv.Users.Messages.Insert("me", msg).Do()
	if err != nil {
		return fmt.Errorf("failed to insert fake email: %w", err)
	}
	msgID := createdMsg.Id
	fmt.Printf("%s Fake email inserted successfully (ID: %s).\n", app.PrefixSuccess, msgID)

	// Defer cleanup of the message
	var msgCleanupErr error
	defer func() {
		if msgID != "" {
			fmt.Printf("%s Step 4: Deleting fake email (ID: %s)...\n", app.PrefixInfo, msgID)
			msgCleanupErr = srv.Users.Messages.Delete("me", msgID).Do()
			if msgCleanupErr != nil {
				if !strings.Contains(msgCleanupErr.Error(), "404") {
					fmt.Printf("%s Failed to delete fake email: %v\n", app.PrefixError, msgCleanupErr)
				}
			} else {
				fmt.Printf("%s Deleted fake email successfully.\n", app.PrefixSuccess)
				msgID = ""
			}
		}
	}()

	// 3. Move the fake email to the created recursive label (remove from INBOX)
	fmt.Printf("%s Step 3: Moving fake email to recursive label %q...\n", app.PrefixInfo, testLabelName)
	_, err = srv.Users.Messages.Modify("me", msgID, &gmailapi.ModifyMessageRequest{
		AddLabelIds:    []string{labelID},
		RemoveLabelIds: []string{"INBOX"},
	}).Do()
	if err != nil {
		return fmt.Errorf("failed to move message: %w", err)
	}
	fmt.Printf("%s Moved email to %q successfully.\n", app.PrefixSuccess, testLabelName)

	// Explicitly perform deletion step now to verify order
	fmt.Printf("%s Step 4: Deleting fake email (ID: %s)...\n", app.PrefixInfo, msgID)
	err = srv.Users.Messages.Delete("me", msgID).Do()
	if err != nil {
		return fmt.Errorf("failed to delete fake email: %w", err)
	}
	msgID = "" // clear it so the deferred cleanup doesn't try to delete it again
	fmt.Printf("%s Deleted fake email successfully.\n", app.PrefixSuccess)

	return nil
}
