package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

var guidSuffixRegex = regexp.MustCompile(`\s*\([0-9a-fA-F-]{6,}\)$`)

func ensureABSIgnore(dir string) error {
	ignorePath := filepath.Join(dir, ".absignore")
	content := "# Audiobookshelf ignore patterns generated by abs\n*.precut\n*.bak\n*.tmp*\n.work/\n"
	if _, err := os.Stat(ignorePath); os.IsNotExist(err) {
		return os.WriteFile(ignorePath, []byte(content), 0644)
	}
	return nil
}

func parseABSEpisodePublishedAt(ep *absEpisode) int64 {
	if ep == nil {
		return 0
	}
	if ep.PublishedAt > 0 {
		return ep.PublishedAt
	}
	if ep.PubDate != "" {
		formats := []string{
			time.RFC1123,
			time.RFC1123Z,
			time.RFC3339,
			time.RFC822,
			time.RFC822Z,
			"2006-01-02 15:04:05",
			"2006-01-02T15:04:05.000Z",
			"2006-01-02",
		}
		for _, f := range formats {
			if t, err := time.Parse(f, strings.TrimSpace(ep.PubDate)); err == nil {
				return t.UnixMilli()
			}
		}
	}
	return 0
}

func normalizeEpisodeTitle(name string) string {
	base := strings.TrimSuffix(name, ".mp3")
	base = guidSuffixRegex.ReplaceAllString(base, "")
	return strings.ToLower(strings.TrimSpace(base))
}

func quarantineFile(path string) error {
	if _, err := os.Stat(path); err != nil {
		return nil
	}
	bakPath := path + ".bak"
	return os.Rename(path, bakPath)
}

func quarantineAbandonedDuplicates(podDir string, trackedEpisodes []absEpisode) []string {
	var quarantined []string

	trackedByNormalized := make(map[string]string)
	trackedFiles := make(map[string]bool)

	for _, ep := range trackedEpisodes {
		fn := ""
		if ep.AudioFile != nil && ep.AudioFile.Metadata.Filename != "" {
			fn = ep.AudioFile.Metadata.Filename
		} else if ep.Title != "" {
			fn = ep.Title + ".mp3"
		}
		if fn != "" {
			trackedFiles[fn] = true
			norm := normalizeEpisodeTitle(fn)
			trackedByNormalized[norm] = fn
		}
	}

	mp3Files, err := filepath.Glob(filepath.Join(podDir, "*.mp3"))
	if err != nil {
		return nil
	}

	for _, mp3 := range mp3Files {
		fn := filepath.Base(mp3)
		if strings.HasSuffix(fn, ".bak") {
			continue
		}

		// If this exact filename is tracked by ABS, it's not abandoned
		if trackedFiles[fn] {
			continue
		}

		norm := normalizeEpisodeTitle(fn)
		// If there is another tracked file with the same normalized title (e.g. one with GUID)
		if trackedFn, exists := trackedByNormalized[norm]; exists && trackedFn != fn {
			// Quarantine this bare/untracked duplicate
			base := strings.TrimSuffix(mp3, ".mp3")

			_ = quarantineFile(mp3)
			_ = quarantineFile(base + ".cuts.json")
			_ = quarantineFile(base + ".transcript.json")
			_ = quarantineFile(mp3 + ".precut")
			_ = quarantineFile(base + ".srt")
			_ = quarantineFile(base + ".txt")

			quarantined = append(quarantined, fn)
		}
	}

	if len(quarantined) > 0 {
		_ = ensureABSIgnore(podDir)
	}

	return quarantined
}

func printQuarantinedSummary(quarantined []string, podName string) {
	if len(quarantined) == 0 {
		return
	}
	fmt.Printf("Quarantined %d abandoned duplicate(s) in '%s' to .bak:\n", len(quarantined), podName)
	for _, q := range quarantined {
		fmt.Printf("  - %s -> %s.bak\n", q, q)
	}
}
